name: Publish public NuGet packages

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0.x' # SDK Version to use
                source-url: https://nuget.pkg.github.com/zachtepper/index.json
              env:
                NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Build
              run: dotnet build --configuration Release TEST_PACKAGE
            - name: Create the package
              run: dotnet pack --configuration release TEST_PACKAGE
            - name: Publish package
              run: dotnet nuget push */bin/Release/*.nupkg